const getters = {
  sidebar: state => state.app.sidebar,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  errorLogs: state => state.errorLog.logs,

  gameMiniList: state => state.baseList.gameMiniList,
  platformList: state => state.baseList.platformList,
  deliveryCompanyList: state => state.baseList.deliveryCompanyList,
  channelList: state => state.baseList.channelList,
  tradeStatusList: state => state.baseList.tradeStatusList,
  sortList: state => state.baseList.sortList,
  areaList: state => state.baseList.areaList,
  groupList: state => state.baseList.groupList,
  languageList: state => state.baseList.languageList,
  definesortList: state => state.baseList.definesortList,
  gameCompanyList: state => state.baseList.gameCompanyList,
  trophyLevelList: state => state.baseList.trophyLevelList,
  contentTypeList: state => state.baseList.contentTypeList,
  contentLocationList: state => state.baseList.contentLocationList,
  checkStatusList: state => state.baseList.checkStatusList,
  trophyList: state => state.baseList.trophyList,
  topicList: state => state.baseList.topicList,
  discStateList: state => state.baseList.discStateList,
}
export default getters
